---
title: "git_00"
author: "Syi-yonnie Richard"
date: "Year 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
One winter night, at half-past nine,  
      Cold, tired, and cross, and muddy,  
I had come home, too late to dine,  
And supper, with cigars and wine,  
      Was waiting in the study.  
      
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
When I see birches bend to left and right  
Across the lines of straighter darker trees,  
I like to think some boy's been swinging them.  
But swinging doesn't bend them down to stay  
As ice-storms do. Often you must have seen them  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Tyger Tyger, burning bright,   
In the forests of the night;   
What immortal hand or eye,   
Could frame thy fearful symmetry?  

In what distant deeps or skies.   
Burnt the fire of thine eyes?  
On what wings dare he aspire?  
What the hand, dare seize the fire?  